services:
  - type: web
    name: neeti-saarthi-backend
    runtime: python
    rootDir: backend
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: gunicorn neeti_vivaad.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: "gemini-2.5-flash"
      - key: OPENROUTER_API_KEY
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "neetisaarthi@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "Neeti Saarthi <neetisaarthi@gmail.com>"
      - key: RECAPTCHA_ENABLED
        value: "False"
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
