'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type SupportedLanguage = 
  | 'en' // English
  | 'hi' // Hindi
  | 'bn' // Bengali
  | 'mr' // Marathi
  | 'ta' // Tamil
  | 'te' // Telugu
  | 'gu' // Gujarati
  | 'kn' // Kannada
  | 'ml' // Malayalam
  | 'pa' // Punjabi
  | 'or'; // Odia

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  speechCode: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', speechCode: 'en-IN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechCode: 'hi-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechCode: 'bn-IN' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechCode: 'mr-IN' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechCode: 'ta-IN' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechCode: 'te-IN' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechCode: 'gu-IN' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechCode: 'kn-IN' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speechCode: 'ml-IN' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', speechCode: 'pa-IN' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', speechCode: 'or-IN' },
];

export const DICTIONARY: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Top Nav
    'nav.home': 'Home',
    'nav.profile': 'My Profile',
    'nav.learn': 'Learn',
    'nav.quiz': 'Knowledge Check',
    'nav.vivaad': 'Neeti Vivaad',
    'nav.admin': 'Admin Overview',
    'nav.explore_courses': 'Explore Courses',
    'nav.sign_in': 'Sign In',
    'nav.sign_out': 'Sign Out',

    // Vivaad Header & Hero
    'vivaad.badge': 'NEETI VIVAAD',
    'vivaad.hero_title': 'Practice real policy decisions.',
    'vivaad.hero_sub': 'Explore a policy situation, consider different perspectives, and make your own decision.',
    'vivaad.prompt_placeholder': 'Describe a policy issue or scenario you want to explore... (e.g. Should our district start school attendance with face recognition?)',
    'vivaad.domain': 'Domain',
    'vivaad.difficulty': 'Difficulty',
    'vivaad.scenario_type': 'Scenario Type',
    'vivaad.upload_doc': 'Upload Document',
    'vivaad.start_btn': 'START VIVAAD',
    'vivaad.generating': 'Generating...',

    // Vivaad 3 Action Cards
    'vivaad.card1_title': 'Upload a Document',
    'vivaad.card1_desc': 'Use a policy report, guideline or article to create a scenario.',
    'vivaad.card1_btn': 'Upload File',
    'vivaad.card2_title': 'Write a Scenario',
    'vivaad.card2_desc': 'Enter a custom issue or question to debate in your own words.',
    'vivaad.card2_btn': 'Get Started',
    'vivaad.card3_title': 'Explore Examples',
    'vivaad.card3_desc': 'Try ready-made scenarios across key domains.',
    'vivaad.card3_btn': 'Browse Examples',

    // Vivaad Try a Scenario Section
    'vivaad.try_section': 'TRY A SCENARIO',
    'vivaad.all': 'All',
    'vivaad.data_privacy': 'Data Privacy',
    'vivaad.ai_gov': 'AI in Governance',
    'vivaad.public_health': 'Public Health',
    'vivaad.edu_policy': 'Education Policy',
    'vivaad.urban_dev': 'Urban Development',
    'vivaad.agriculture': 'Agriculture',

    // Step 1: Understand
    'step.1': '1. Understand',
    'step.2': '2. Different Views',
    'step.3': '3. Your Choice',
    'step.4': '4. Explain',
    'step.5': '5. Learn',
    'vivaad.what_happening': 'What is happening?',
    'vivaad.why_matter': 'WHY DOES IT MATTER?',
    'vivaad.read_more': 'Read more',
    'vivaad.read_less': 'Show less',
    'vivaad.continue_views': 'See Different Views',
    'vivaad.exit': 'Exit to Scenarios',

    // Step 2: Different Views
    'vivaad.different_views_title': 'DIFFERENT VIEWS',
    'vivaad.different_views_desc': 'Before making a decision, see what different people think about this situation.',
    'vivaad.ask_question': 'Ask a Question',
    'vivaad.close_question': 'Close Discussion',
    'vivaad.type_question_placeholder': 'Ask this person a question...',
    'vivaad.send': 'Send',
    'vivaad.continue_choice': 'Make Your Choice',
    'vivaad.back': 'Back',

    // Step 3: Your Choice
    'vivaad.your_choice_title': 'WHAT WOULD YOU DO?',
    'vivaad.your_choice_desc': 'Choose the option that seems best to you. There is no single correct answer — your reasoning matters.',
    'vivaad.continue_explain': 'Explain Your Choice',

    // Step 4: Explain
    'vivaad.explain_title': 'WHY DID YOU CHOOSE THIS?',
    'vivaad.explain_desc': 'Tell us what made you choose this option. Explain in your own words.',
    'vivaad.explain_placeholder': 'Explain in your own words what made you pick this choice, and what things should be taken care of...',
    'vivaad.speak_btn': 'Speak',
    'vivaad.listening': 'Listening... (Speak now in your language)',
    'vivaad.stop_listening': 'Stop Listening',
    'vivaad.speech_not_supported': 'Voice input is not supported in this browser. Please type your explanation.',
    'vivaad.submit_decision': 'Submit Decision',
    'vivaad.submitting': 'Evaluating Reasoning...',

    // Step 5: Learn / Feedback
    'vivaad.feedback_title': 'HERE IS HOW YOUR REASONING HELD UP',
    'vivaad.your_decision': 'YOUR DECISION',
    'vivaad.you_chose': 'You chose:',
    'vivaad.makes_sense': 'THAT MAKES SENSE BECAUSE...',
    'vivaad.think_about': 'THINK ABOUT THIS TOO...',
    'vivaad.another_view': 'ANOTHER VIEW TO CONSIDER',
    'vivaad.see_details': 'See Detailed Assessment',
    'vivaad.hide_details': 'Hide Detailed Assessment',
    'vivaad.try_another': 'Try Another Scenario',
    'vivaad.try_again': 'Try This Scenario Again',

    // Buddy Prompts
    'buddy.vivaad_help': 'Need help understanding this scenario?',
    'buddy.vivaad_explain_simple': 'Can you explain this scenario in simple terms?',
    'buddy.vivaad_views_help': 'Why do people have different views on this?',
    'buddy.vivaad_think_help': 'What should I think about before deciding?',
  },

  hi: {
    // Top Nav
    'nav.home': 'होम',
    'nav.profile': 'मेरी प्रोफाइल',
    'nav.learn': 'सीखें',
    'nav.quiz': 'ज्ञान परख',
    'nav.vivaad': 'नीति विवाद',
    'nav.admin': 'प्रशासन',
    'nav.explore_courses': 'कोर्स देखें',
    'nav.sign_in': 'साइन इन',
    'nav.sign_out': 'लॉग आउट',

    // Vivaad Header & Hero
    'vivaad.badge': 'नीति विवाद',
    'vivaad.hero_title': 'वास्तविक नीतिगत फैसलों का अभ्यास करें।',
    'vivaad.hero_sub': 'स्थिति को समझें, अलग-अलग लोगों का नज़रिया देखें, और अपनी समझ से फैसला लें।',
    'vivaad.prompt_placeholder': 'वह नीतिगत मुद्दा या स्थिति लिखें जिसे आप समझना चाहते हैं... (उदा. क्या हमारे जिले में सरकारी स्कूलों में चेहरे की पहचान से हाज़िरी लगानी चाहिए?)',
    'vivaad.domain': 'विषय',
    'vivaad.difficulty': 'कठिनाई',
    'vivaad.scenario_type': 'फैसले का प्रकार',
    'vivaad.upload_doc': 'दस्तावेज़ जोड़ें',
    'vivaad.start_btn': 'विवाद शुरू करें',
    'vivaad.generating': 'तैयार हो रहा है...',

    // Vivaad 3 Action Cards
    'vivaad.card1_title': 'दस्तावेज़ अपलोड करें',
    'vivaad.card1_desc': 'किसी सरकारी रिपोर्ट, नियम या परिपत्र से नया फैसला अभ्यास बनाएं।',
    'vivaad.card1_btn': 'फ़ाइल अपलोड करें',
    'vivaad.card2_title': 'अपनी स्थिति लिखें',
    'vivaad.card2_desc': 'अपने शब्दों में कोई स्थानीय या प्रशासनिक दुविधा लिखें।',
    'vivaad.card2_btn': 'शुरू करें',
    'vivaad.card3_title': 'उदाहरण देखें',
    'vivaad.card3_desc': 'अलग-अलग क्षेत्रों के पहले से तैयार नीतिगत उदाहरण देखें।',
    'vivaad.card3_btn': 'उदाहरण देखें',

    // Vivaad Try a Scenario Section
    'vivaad.try_section': 'कोई स्थिति चुनकर अभ्यास करें',
    'vivaad.all': 'सभी',
    'vivaad.data_privacy': 'डेटा व निजता',
    'vivaad.ai_gov': 'एआई और शासन',
    'vivaad.public_health': 'जन स्वास्थ्य',
    'vivaad.edu_policy': 'शिक्षा नीति',
    'vivaad.urban_dev': 'शहरी विकास',
    'vivaad.agriculture': 'कृषि व ग्रामीण',

    // Step 1: Understand
    'step.1': '1. स्थिति समझें',
    'step.2': '2. अलग-अलग राय',
    'step.3': '3. आपकी पसंद',
    'step.4': '4. कारण बताएं',
    'step.5': '5. सीखें',
    'vivaad.what_happening': 'स्थिति क्या है?',
    'vivaad.why_matter': 'यह फैसला क्यों महत्वपूर्ण है?',
    'vivaad.read_more': 'और विस्तार से पढ़ें',
    'vivaad.read_less': 'कम दिखाएं',
    'vivaad.continue_views': 'लोगों की राय देखें',
    'vivaad.exit': 'बाहर निकलें',

    // Step 2: Different Views
    'vivaad.different_views_title': 'अलग-अलग राय',
    'vivaad.different_views_desc': 'फैसले से पहले देखें कि इस स्थिति पर अलग-अलग लोगों का क्या सोचना है।',
    'vivaad.ask_question': 'सवाल पूछें',
    'vivaad.close_question': 'बातचीत बंद करें',
    'vivaad.type_question_placeholder': 'इस व्यक्ति से अपना सवाल पूछें...',
    'vivaad.send': 'भेजें',
    'vivaad.continue_choice': 'अपना फैसला चुनें',
    'vivaad.back': 'पीछे जाएं',

    // Step 3: Your Choice
    'vivaad.your_choice_title': 'आप क्या करेंगे?',
    'vivaad.your_choice_desc': 'वह विकल्प चुनें जो आपको सबसे सही लगता है। कोई एक सही जवाब नहीं है — आपका सोचना मायने रखता है।',
    'vivaad.continue_explain': 'कारण बताएं',

    // Step 4: Explain
    'vivaad.explain_title': 'आपने यह विकल्प क्यों चुना?',
    'vivaad.explain_desc': 'अपने शब्दों में बताएं कि आपने यह फैसला क्यों लिया।',
    'vivaad.explain_placeholder': 'अपने शब्दों में बताएं कि आपको यह विकल्प क्यों सही लगा, और किन बातों का ध्यान रखना चाहिए...',
    'vivaad.speak_btn': 'बोलकर बताएं',
    'vivaad.listening': 'सुन रहे हैं... (अब अपनी भाषा में बोलें)',
    'vivaad.stop_listening': 'बोलना बंद करें',
    'vivaad.speech_not_supported': 'इस ब्राउज़र में आवाज़ इनपुट उपलब्ध नहीं है। कृपया लिखकर बताएं।',
    'vivaad.submit_decision': 'फैसला जमा करें',
    'vivaad.submitting': 'मूल्यांकन हो रहा है...',

    // Step 5: Learn / Feedback
    'vivaad.feedback_title': 'आपके फैसले का विश्लेषण',
    'vivaad.your_decision': 'आपका फैसला',
    'vivaad.you_chose': 'आपने चुना:',
    'vivaad.makes_sense': 'यह समझ में आता है क्योंकि...',
    'vivaad.think_about': 'इस बात पर भी सोचें...',
    'vivaad.another_view': 'दूसरा नज़रिया',
    'vivaad.see_details': 'विस्तृत योग्यता विश्लेषण देखें',
    'vivaad.hide_details': 'विस्तृत विश्लेषण छुपाएं',
    'vivaad.try_another': 'दूसरा फैसला आज़माएं',
    'vivaad.try_again': 'इसे दोबारा आज़माएं',

    // Buddy Prompts
    'buddy.vivaad_help': 'क्या इस फैसले को समझने में मदद चाहिए?',
    'buddy.vivaad_explain_simple': 'क्या आप इसे आसान हिंदी में समझा सकते हैं?',
    'buddy.vivaad_views_help': 'इस पर लोगों की राय अलग क्यों है?',
    'buddy.vivaad_think_help': 'फैसला लेने से पहले मुझे क्या सोचना चाहिए?',
  },

  bn: {
    'nav.home': 'হোম',
    'nav.profile': 'আমার প্রোফাইল',
    'nav.learn': 'শিখুন',
    'nav.quiz': 'জ্ঞান পরীক্ষা',
    'nav.vivaad': 'নীতি বিবাদ',
    'nav.admin': 'প্রশাসন',
    'nav.explore_courses': 'কোর্স দেখুন',
    'nav.sign_in': 'সাইন ইন',
    'nav.sign_out': 'লগ আউট',
    'vivaad.badge': 'নীতি বিবাদ',
    'vivaad.hero_title': 'বাস্তব নীতিগত সিদ্ধান্তের অনুশীলন করুন।',
    'vivaad.hero_sub': 'পরিস্থিতি বুঝুন, ভিন্ন দৃষ্টিভঙ্গি দেখুন এবং নিজের সিদ্ধান্ত নিন।',
    'vivaad.prompt_placeholder': 'যে নীতিগত বিষয়টি অন্বেষণ করতে চান তা লিখুন...',
    'vivaad.domain': 'বিষয়',
    'vivaad.difficulty': 'কঠিনতা',
    'vivaad.scenario_type': 'ধরন',
    'vivaad.upload_doc': 'ডকুমেন্ট আপলোড',
    'vivaad.start_btn': 'শুরু করুন',
    'vivaad.generating': 'প্রস্তুত হচ্ছে...',
    'vivaad.card1_title': 'ডকুমেন্ট আপলোড করুন',
    'vivaad.card1_desc': 'একটি সরকারি নির্দেশিকা বা রিপোর্ট থেকে সিদ্ধান্ত তৈরি করুন।',
    'vivaad.card1_btn': 'ফাইল আপলোড',
    'vivaad.card2_title': 'পরিস্থিতি লিখুন',
    'vivaad.card2_desc': 'নিজের ভাষায় একটি স্থানীয় প্রশাসনিক সমস্যা লিখুন।',
    'vivaad.card2_btn': 'শুরু করুন',
    'vivaad.card3_title': 'উদাহরণ দেখুন',
    'vivaad.card3_desc': 'বিভিন্ন ক্ষেত্রের প্রস্তুত সিদ্ধান্ত অনুশীলন দেখুন।',
    'vivaad.card3_btn': 'উদাহরণ দেখুন',
    'vivaad.try_section': 'একটি পরিস্থিতি বেছে নিন',
    'vivaad.all': 'সব',
    'vivaad.data_privacy': 'তথ্য ও গোপনীয়তা',
    'vivaad.ai_gov': 'এআই ও প্রশাসন',
    'vivaad.public_health': 'জনস্বাস্থ্য',
    'vivaad.edu_policy': 'শিক্ষা নীতি',
    'vivaad.urban_dev': 'নগর উন্নয়ন',
    'vivaad.agriculture': 'কৃষি ও গ্রামীন',
    'step.1': '১. বুঝুন',
    'step.2': '২. বিভিন্ন মতামত',
    'step.3': '৩. আপনার পছন্দ',
    'step.4': '৪. ব্যাখ্যা দিন',
    'step.5': '৫. শিখুন',
    'vivaad.what_happening': 'কী ঘটছে?',
    'vivaad.why_matter': 'এটি কেন গুরুত্বপূর্ণ?',
    'vivaad.read_more': 'আরও পড়ুন',
    'vivaad.read_less': 'সংক্ষেপে দেখুন',
    'vivaad.continue_views': 'বিভিন্ন মতামত দেখুন',
    'vivaad.exit': 'প্রস্থান',
    'vivaad.different_views_title': 'বিভিন্ন মতামত',
    'vivaad.different_views_desc': 'সিদ্ধান্ত নেওয়ার আগে দেখুন বিভিন্ন মানুষ কী ভাবছেন।',
    'vivaad.ask_question': 'প্রশ্ন জিজ্ঞাসা করুন',
    'vivaad.close_question': 'কথোপকথন বন্ধ করুন',
    'vivaad.type_question_placeholder': 'আপনার প্রশ্ন জিজ্ঞাসা করুন...',
    'vivaad.send': 'পাঠান',
    'vivaad.continue_choice': 'আপনার সিদ্ধান্ত নিন',
    'vivaad.back': 'ফিরে যান',
    'vivaad.your_choice_title': 'আপনি কী করবেন?',
    'vivaad.your_choice_desc': 'আপনার সবচেয়ে উপযুক্ত মনে হওয়া বিকল্পটি নির্বাচন করুন।',
    'vivaad.continue_explain': 'কারণ ব্যাখ্যা করুন',
    'vivaad.explain_title': 'আপনি এটি কেন বেছে নিলেন?',
    'vivaad.explain_desc': 'নিজের ভাষায় জানান কেন এই বিকল্পটি বেছে নিয়েছেন।',
    'vivaad.explain_placeholder': 'নিজের ভাষায় ব্যাখ্যা করুন...',
    'vivaad.speak_btn': 'মুখে বলুন',
    'vivaad.listening': 'শুনছি... (এখন বলুন)',
    'vivaad.stop_listening': 'থামুন',
    'vivaad.speech_not_supported': 'ভয়েস সমর্থিত নয়। অনুগ্রহ করে লিখে জানান।',
    'vivaad.submit_decision': 'সিদ্ধান্ত জমা দিন',
    'vivaad.submitting': 'বিশ্লেষণ চলছে...',
    'vivaad.feedback_title': 'আপনার সিদ্ধান্তের পর্যালোচনা',
    'vivaad.your_decision': 'আপনার সিদ্ধান্ত',
    'vivaad.you_chose': 'আপনি বেছে নিয়েছেন:',
    'vivaad.makes_sense': 'এটি যুক্তিসঙ্গত কারণ...',
    'vivaad.think_about': 'এটিও ভেবে দেখুন...',
    'vivaad.another_view': 'অন্য দৃষ্টিভঙ্গি',
    'vivaad.see_details': 'বিস্তারিত দেখুন',
    'vivaad.hide_details': 'লুকান',
    'vivaad.try_another': 'আরেকটি সিদ্ধান্ত দেখুন',
    'vivaad.try_again': 'আবার চেষ্টা করুন',
    'buddy.vivaad_help': 'সহায়তা প্রয়োজন?',
    'buddy.vivaad_explain_simple': 'এটি সহজে বোঝাতে পারেন?',
    'buddy.vivaad_views_help': 'মতামতের পার্থক্য কেন?',
    'buddy.vivaad_think_help': 'আমার কী বিবেচনা করা উচিত?',
  },

  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.profile': 'माझे प्रोफाइल',
    'nav.learn': 'शिका',
    'nav.quiz': 'ज्ञान चाचणी',
    'nav.vivaad': 'नीती विवाद',
    'nav.admin': 'प्रशासन',
    'nav.explore_courses': 'कोर्स एक्सप्लोर करा',
    'nav.sign_in': 'साइन इन',
    'nav.sign_out': 'साइन आउट',
    'vivaad.badge': 'नीती विवाद',
    'vivaad.hero_title': 'खऱ्या धोरणात्मक निर्णयांचा सराव करा.',
    'vivaad.hero_sub': 'परिस्थिती समजून घ्या, विविध दृष्टिकोन तपासा आणि स्वतःचा निर्णय घ्या.',
    'vivaad.prompt_placeholder': 'तुम्हाला हाताळायचा असलेला धोरणात्मक मुद्दा लिहा...',
    'vivaad.domain': 'क्षेत्र',
    'vivaad.difficulty': 'काठिण्य',
    'vivaad.scenario_type': 'प्रकार',
    'vivaad.upload_doc': 'कागदपत्र जोडा',
    'vivaad.start_btn': 'सुरू करा',
    'vivaad.generating': 'तयार होत आहे...',
    'vivaad.card1_title': 'कागदपत्र अपलोड करा',
    'vivaad.card1_desc': 'परिपत्रक किंवा अहवालावरून सराव परिस्थिती तयार करा.',
    'vivaad.card1_btn': 'फाइल अपलोड करा',
    'vivaad.card2_title': 'परिस्थिती लिहा',
    'vivaad.card2_desc': 'तुमच्या स्वतःच्या शब्दांत स्थानिक प्रशासकीय समस्या मांडा.',
    'vivaad.card2_btn': 'सुरू करा',
    'vivaad.card3_title': 'उदाहरणे पहा',
    'vivaad.card3_desc': 'तयार धोरणात्मक निर्णय परिस्थितीचा सराव करा.',
    'vivaad.card3_btn': 'उदाहरणे पहा',
    'vivaad.try_section': 'एक परिस्थिती निवडा',
    'vivaad.all': 'सर्व',
    'vivaad.data_privacy': 'डेटा व गोपनीयता',
    'vivaad.ai_gov': 'एआय व प्रशासन',
    'vivaad.public_health': 'सार्वजनिक आरोग्य',
    'vivaad.edu_policy': 'शिक्षण धोरण',
    'vivaad.urban_dev': 'शहरी विकास',
    'vivaad.agriculture': 'शेती व ग्रामीण विकास',
    'step.1': '१. समजून घ्या',
    'step.2': '२. विविध मते',
    'step.3': '३. तुमचा निर्णय',
    'step.4': '४. कारण सांगा',
    'step.5': '५. शिका',
    'vivaad.what_happening': 'नेमके काय घडत आहे?',
    'vivaad.why_matter': 'हे का महत्त्वाचे आहे?',
    'vivaad.read_more': 'अधिक वाचा',
    'vivaad.read_less': 'कमी करा',
    'vivaad.continue_views': 'विविध दृष्टिकोन पहा',
    'vivaad.exit': 'बाहेर पडा',
    'vivaad.different_views_title': 'विविध मते',
    'vivaad.different_views_desc': 'निर्णय घेण्यापूर्वी विविध घटकांचे मत काय आहे ते पहा.',
    'vivaad.ask_question': 'प्रश्न विचारा',
    'vivaad.close_question': 'बंद करा',
    'vivaad.type_question_placeholder': 'प्रश्न विचारा...',
    'vivaad.send': 'पाठवा',
    'vivaad.continue_choice': 'तुमचा निर्णय निवडा',
    'vivaad.back': 'मागे जा',
    'vivaad.your_choice_title': 'तुम्ही काय कराल?',
    'vivaad.your_choice_desc': 'तुम्हाला सर्वात योग्य वाटणारा पर्याय निवडा.',
    'vivaad.continue_explain': 'कारण स्पष्ट करा',
    'vivaad.explain_title': 'तुम्ही हा पर्याय का निवडला?',
    'vivaad.explain_desc': 'तुमच्या स्वतःच्या शब्दांत सांगा.',
    'vivaad.explain_placeholder': 'स्वतःच्या शब्दांत स्पष्ट करा...',
    'vivaad.speak_btn': 'बोलून सांगा',
    'vivaad.listening': 'ऐकत आहोत... (बोला)',
    'vivaad.stop_listening': 'थांबा',
    'vivaad.speech_not_supported': 'व्हॉइस इनपुट उपलब्ध नाही. टाईप करा.',
    'vivaad.submit_decision': 'निर्णय सबमिट करा',
    'vivaad.submitting': 'मूल्यांकन होत आहे...',
    'vivaad.feedback_title': 'तुमच्या निर्णयाचे मूल्यमापन',
    'vivaad.your_decision': 'तुमचा निर्णय',
    'vivaad.you_chose': 'तुम्ही निवडले:',
    'vivaad.makes_sense': 'हे योग्य वाटते कारण...',
    'vivaad.think_about': 'याचाही विचार करा...',
    'vivaad.another_view': 'दुसरा दृष्टिकोन',
    'vivaad.see_details': 'सविस्तर विश्लेषण पहा',
    'vivaad.hide_details': 'लपवा',
    'vivaad.try_another': 'दुसरा प्रसंग पहा',
    'vivaad.try_again': 'पुन्हा प्रयत्न करा',
    'buddy.vivaad_help': 'मदत हवी आहे का?',
    'buddy.vivaad_explain_simple': 'सोप्या भाषेत समजावून सांगू शकाल का?',
    'buddy.vivaad_views_help': 'मतांमध्ये फरक का आहे?',
    'buddy.vivaad_think_help': 'मी कशाचा विचार करावा?',
  },

  ta: {
    'nav.home': 'முகப்பு',
    'nav.profile': 'எனது சுயவிவரம்',
    'nav.learn': 'கற்க',
    'nav.quiz': 'அறிவுத் தேர்வு',
    'nav.vivaad': 'நீதி விவாதம்',
    'nav.admin': 'நிர்வாகம்',
    'nav.explore_courses': 'பாடப்பிரிவுகளைப் பார்க்க',
    'nav.sign_in': 'உள்நுழைக',
    'nav.sign_out': 'வெளியேறுக',
    'vivaad.badge': 'நீதி விவாதம்',
    'vivaad.hero_title': 'நடைமுறை கொள்கை முடிவுகளைப் பயிற்சி செய்க.',
    'vivaad.hero_sub': 'சூழ்நிலையைப் புரிந்து கொண்டு, பல கோணங்களை ஆராய்ந்து, உங்கள் முடிவை எடுங்கள்.',
    'vivaad.prompt_placeholder': 'நீங்கள் ஆராய விரும்பும் கொள்கைப் பிரச்சினையை விவரிக்கவும்...',
    'vivaad.domain': 'துறை',
    'vivaad.difficulty': 'கடினம்',
    'vivaad.scenario_type': 'வகை',
    'vivaad.upload_doc': 'ஆவணத்தைப் பதிவேற்றுக',
    'vivaad.start_btn': 'தொடங்குக',
    'vivaad.generating': 'உருவாகிறது...',
    'vivaad.card1_title': 'ஆவணத்தைப் பதிவேற்றுக',
    'vivaad.card1_desc': 'அரசு வழிகாட்டுதல் அல்லது அறிக்கையிலிருந்து பயிற்சியை உருவாக்குங்கள்.',
    'vivaad.card1_btn': 'பதிவேற்று',
    'vivaad.card2_title': 'சூழ்நிலையை எழுதுங்கள்',
    'vivaad.card2_desc': 'உங்கள் சொந்த வார்த்தைகளில் நிர்வாகப் பிரச்சினையை எழுதுங்கள்.',
    'vivaad.card2_btn': 'தொடங்கு',
    'vivaad.card3_title': 'எடுத்துக்காட்டுகளைக் காண்க',
    'vivaad.card3_desc': 'முக்கிய துறைகளில் ஏற்கனவே உள்ள கொள்கை சூழ்நிலைகளைப் பயிற்சி செய்யுங்கள்.',
    'vivaad.card3_btn': 'பார்வையிடு',
    'vivaad.try_section': 'ஒரு சூழ்நிலையைத் தேர்வு செய்யவும்',
    'vivaad.all': 'அனைத்தும்',
    'vivaad.data_privacy': 'தரவு மற்றும் தனியுரிமை',
    'vivaad.ai_gov': 'AI மற்றும் ஆளுகை',
    'vivaad.public_health': 'பொது சுகாதாரம்',
    'vivaad.edu_policy': 'கல்விக் கொள்கை',
    'vivaad.urban_dev': 'நகர்ப்புற வளர்ச்சி',
    'vivaad.agriculture': 'விவசாயம்',
    'step.1': '1. புரிந்துகொள்க',
    'step.2': '2. மாறுபட்ட கருத்துக்கள்',
    'step.3': '3. உங்கள் முடிவு',
    'step.4': '4. காரணம் கூறுக',
    'step.5': '5. கற்க',
    'vivaad.what_happening': 'என்ன நடக்கிறது?',
    'vivaad.why_matter': 'இது ஏன் முக்கியமானது?',
    'vivaad.read_more': 'மேலும் படிக்க',
    'vivaad.read_less': 'குறைக்க',
    'vivaad.continue_views': 'மாறுபட்ட கருத்துக்களைக் காண்க',
    'vivaad.exit': 'வெளியேறு',
    'vivaad.different_views_title': 'மாறுபட்ட கருத்துக்கள்',
    'vivaad.different_views_desc': 'முடிவெடுக்கும் முன் பலரின் கருத்துக்களை அறிந்து கொள்ளுங்கள்.',
    'vivaad.ask_question': 'கேள்வி கேட்க',
    'vivaad.close_question': 'மூடு',
    'vivaad.type_question_placeholder': 'கேள்வி கேளுங்கள்...',
    'vivaad.send': 'அனுப்பு',
    'vivaad.continue_choice': 'உங்கள் முடிவைத் தேர்ந்தெடுங்கள்',
    'vivaad.back': 'பின்செல்',
    'vivaad.your_choice_title': 'நீங்கள் என்ன செய்வீர்கள்?',
    'vivaad.your_choice_desc': 'உங்களுக்குச் சிறந்ததாகத் தோன்றும் விருப்பத்தைத் தேர்ந்தெடுங்கள்.',
    'vivaad.continue_explain': 'விளக்கம் தருக',
    'vivaad.explain_title': 'இதை ஏன் தேர்ந்தெடுத்தீர்கள்?',
    'vivaad.explain_desc': 'உங்கள் சொந்த வார்த்தைகளில் சொல்லுங்கள்.',
    'vivaad.explain_placeholder': 'உங்கள் வார்த்தைகளில் விளக்குங்கள்...',
    'vivaad.speak_btn': 'பேசி விளக்குக',
    'vivaad.listening': 'கேட்கிறது... (பேசுங்கள்)',
    'vivaad.stop_listening': 'நிறுத்து',
    'vivaad.speech_not_supported': 'குரல் உள்ளீடு இல்லை. தட்டச்சு செய்யுங்கள்.',
    'vivaad.submit_decision': 'முடிவைச் சமர்ப்பிக்கவும்',
    'vivaad.submitting': 'மதிப்பாய்வு செய்யப்படுகிறது...',
    'vivaad.feedback_title': 'உங்கள் முடிவின் மதிப்பீடு',
    'vivaad.your_decision': 'உங்கள் முடிவு',
    'vivaad.you_chose': 'நீங்கள் தேர்ந்தெடுத்தது:',
    'vivaad.makes_sense': 'இது நியாயமானது ஏனெனில்...',
    'vivaad.think_about': 'இதையும் சிந்தியுங்கள்...',
    'vivaad.another_view': 'மற்றொரு கோணம்',
    'vivaad.see_details': 'விவரங்களைக் காண்க',
    'vivaad.hide_details': 'மறைக்க',
    'vivaad.try_another': 'வேறொன்றை முயற்சிக்கவும்',
    'vivaad.try_again': 'மீண்டும் முயற்சிக்கவும்',
    'buddy.vivaad_help': 'உதவி தேவையா?',
    'buddy.vivaad_explain_simple': 'எளிய தமிழில் விளக்க முடியுமா?',
    'buddy.vivaad_views_help': 'கருத்து வேறுபாடு ஏன்?',
    'buddy.vivaad_think_help': 'நான் எதைச் சிந்திக்க வேண்டும்?',
  },

  te: {
    'nav.home': 'హోమ్',
    'nav.profile': 'నా ప్రొఫైల్',
    'nav.learn': 'నేర్చుకోండి',
    'nav.quiz': 'జ్ఞాన పరీక్ష',
    'nav.vivaad': 'నీతి వివాదం',
    'nav.admin': 'నిర్వహణ',
    'nav.explore_courses': 'కోర్సులు చూడండి',
    'nav.sign_in': 'సైన్ ఇన్',
    'nav.sign_out': 'లాగ్ అవుట్',
    'vivaad.badge': 'నీతి వివాదం',
    'vivaad.hero_title': 'వాస్తవ విధాన నిర్ణయాలను సాధన చేయండి.',
    'vivaad.hero_sub': 'పరిస్థితిని అర్థం చేసుకోండి, భిన్న దృక్కోణాలను పరిశీలించండి, మరియు మీ స్వంత నిర్ణయం తీసుకోండి.',
    'vivaad.prompt_placeholder': 'మీరు అన్వేషించాలనుకుంటున్న విధాన సమస్యను వివరించండి...',
    'vivaad.domain': 'రంగం',
    'vivaad.difficulty': 'స్థాయి',
    'vivaad.scenario_type': 'రకం',
    'vivaad.upload_doc': 'పత్రం అప్‌లోడ్',
    'vivaad.start_btn': 'ప్రారంభించండి',
    'vivaad.generating': 'రూపొందిస్తోంది...',
    'vivaad.card1_title': 'పత్రాన్ని అప్‌లోడ్ చేయండి',
    'vivaad.card1_desc': 'మార్గాదర్శకాలు లేదా నివేదిక నుండి దృశ్యాన్ని సృష్టించండి.',
    'vivaad.card1_btn': 'అప్‌లోడ్ చేయండి',
    'vivaad.card2_title': 'సమస్యను రాయండి',
    'vivaad.card2_desc': 'మీ స్వంత మాటల్లో పరిపాలనా సమస్యను రాయండి.',
    'vivaad.card2_btn': 'ప్రారంభించండి',
    'vivaad.card3_title': 'ఉదాహరణలు చూడండి',
    'vivaad.card3_desc': 'ముఖ్య రంగాలలో సిద్ధంగా ఉన్న నిర్ణయ పరిస్థితులను ప్రయత్నించండి.',
    'vivaad.card3_btn': 'చూడండి',
    'vivaad.try_section': 'ఒక పరిస్థితిని ఎంచుకోండి',
    'vivaad.all': 'అన్నీ',
    'vivaad.data_privacy': 'డేటా & గోప్యత',
    'vivaad.ai_gov': 'AI & పాలన',
    'vivaad.public_health': 'ప్రజారోగ్యం',
    'vivaad.edu_policy': 'విద్యా విధానం',
    'vivaad.urban_dev': 'పట్టణాభివృద్ధి',
    'vivaad.agriculture': 'వ్యవసాయం',
    'step.1': '1. అర్థం చేసుకోండి',
    'step.2': '2. విభిన్న అభిప్రాయాలు',
    'step.3': '3. మీ ఎంపిక',
    'step.4': '4. వివరించండి',
    'step.5': '5. నేర్చుకోండి',
    'vivaad.what_happening': 'ఏం జరుగుతోంది?',
    'vivaad.why_matter': 'ఇది ఎందుకు ముఖ్యం?',
    'vivaad.read_more': 'మరింత చదవండి',
    'vivaad.read_less': 'తగ్గించండి',
    'vivaad.continue_views': 'విభిన్న అభిప్రాయాలు చూడండి',
    'vivaad.exit': 'నిష్క్రమించండి',
    'vivaad.different_views_title': 'విభిన్న అభిప్రాయాలు',
    'vivaad.different_views_desc': 'నిర్ణయం తీసుకునే ముందు ఇతరుల అభిప్రాయాలను తెలుసుకోండి.',
    'vivaad.ask_question': 'ప్రశ్న అడగండి',
    'vivaad.close_question': 'ముగించండి',
    'vivaad.type_question_placeholder': 'ప్రశ్న అడగండి...',
    'vivaad.send': 'పంపండి',
    'vivaad.continue_choice': 'మీ నిర్ణయం ఎంచుకోండి',
    'vivaad.back': 'వెనుకకు',
    'vivaad.your_choice_title': 'మీరు ఏమి చేస్తారు?',
    'vivaad.your_choice_desc': 'మీకు సరైనదని భావించే ఎంపికను ఎంచుకోండి.',
    'vivaad.continue_explain': 'వివరించండి',
    'vivaad.explain_title': 'మీరు దీన్ని ఎందుకు ఎంచుకున్నారు?',
    'vivaad.explain_desc': 'మీ స్వంత మాటల్లో తెలియజేయండి.',
    'vivaad.explain_placeholder': 'మీ మాటల్లో వివరించండి...',
    'vivaad.speak_btn': 'మాట్లాడి చెప్పండి',
    'vivaad.listening': 'వింటోంది... (మాట్లాడండి)',
    'vivaad.stop_listening': 'ఆపండి',
    'vivaad.speech_not_supported': 'వాయిస్ సపోర్ట్ లేదు. దయచేసి టైప్ చేయండి.',
    'vivaad.submit_decision': 'సమర్పించండి',
    'vivaad.submitting': 'విశ్లేషిస్తోంది...',
    'vivaad.feedback_title': 'మీ నిర్ణయ మూల్యాంకనం',
    'vivaad.your_decision': 'మీ నిర్ణయం',
    'vivaad.you_chose': 'మీరు ఎంచుకున్నది:',
    'vivaad.makes_sense': 'ఇది సహేతుకం ఎందుకంటే...',
    'vivaad.think_about': 'దీని గురించి కూడా ఆలోచించండి...',
    'vivaad.another_view': 'మరో దృక్కోణం',
    'vivaad.see_details': 'వివరాలు చూడండి',
    'vivaad.hide_details': 'దాచండి',
    'vivaad.try_another': 'మరొకటి ప్రయత్నించండి',
    'vivaad.try_again': 'మళ్లీ ప్రయత్నించండి',
    'buddy.vivaad_help': 'సహాయం కావాలా?',
    'buddy.vivaad_explain_simple': 'సులభంగా వివరించగలరా?',
    'buddy.vivaad_views_help': 'అభిప్రాయాలు ఎందుకు వేరుగా ఉన్నాయి?',
    'buddy.vivaad_think_help': 'నేను ఏమి ఆలోచించాలి?',
  },

  gu: {
    'nav.home': 'હોમ',
    'nav.profile': 'મારી પ્રોફાઇલ',
    'nav.learn': 'શીખો',
    'nav.quiz': 'જ્ઞાન કસોટી',
    'nav.vivaad': 'નીતિ વિવાદ',
    'nav.admin': 'વહીવટ',
    'nav.explore_courses': 'કોર્સ જુઓ',
    'nav.sign_in': 'સાઇન ઇન',
    'nav.sign_out': 'લૉગ આઉટ',
    'vivaad.badge': 'નીતિ વિવાદ',
    'vivaad.hero_title': 'વાસ્તવિક નીતિ વિષયક નિર્ણયોનો અભ્યાસ કરો.',
    'vivaad.hero_sub': 'સ્થિતિ સમજો, અલગ અલગ મંતવ્યો જાણો અને તમારો પોતાનો નિર્ણય લો.',
    'vivaad.prompt_placeholder': 'તમે જે નીતિ વિષયક મુદ્દા પર વિચારવા માંગો છો તે લખો...',
    'vivaad.domain': 'ક્ષેત્ર',
    'vivaad.difficulty': 'કઠિનતા',
    'vivaad.scenario_type': 'પ્રકાર',
    'vivaad.upload_doc': 'દસ્તાવેજ જોડો',
    'vivaad.start_btn': 'શરૂ કરો',
    'vivaad.generating': 'તૈયાર થાય છે...',
    'vivaad.card1_title': 'દસ્તાવેજ અપલોડ કરો',
    'vivaad.card1_desc': 'સરકારી પરિપત્ર અથવા અહેવાલમાંથી નિર્ણય પરિસ્થિતિ બનાવો.',
    'vivaad.card1_btn': 'અપલોડ કરો',
    'vivaad.card2_title': 'સ્થિતિ લખો',
    'vivaad.card2_desc': 'તમારા પોતાના શબ્દોમાં સ્થાનિક વહીવટી પ્રશ્ન લખો.',
    'vivaad.card2_btn': 'શરૂ કરો',
    'vivaad.card3_title': 'ઉદાહરણો જુઓ',
    'vivaad.card3_desc': 'તૈયાર નીતિ વિષયક નિર્ણયોનો અભ્યાસ કરો.',
    'vivaad.card3_btn': 'જુઓ',
    'vivaad.try_section': 'એક પરિસ્થિતિ પસંદ કરો',
    'vivaad.all': 'બધા',
    'vivaad.data_privacy': 'ડેટા અને પ્રાઇવસી',
    'vivaad.ai_gov': 'એઆઈ અને શાસન',
    'vivaad.public_health': 'જાહેર આરોગ્ય',
    'vivaad.edu_policy': 'શિક્ષણ નીતિ',
    'vivaad.urban_dev': 'શહેરી વિકાસ',
    'vivaad.agriculture': 'કૃષિ અને ગ્રામીણ',
    'step.1': '૧. સમજો',
    'step.2': '૨. અલગ અલગ મંતવ્યો',
    'step.3': '૩. તમારી પસંદગી',
    'step.4': '૪. સમજાવો',
    'step.5': '૫. શીખો',
    'vivaad.what_happening': 'શું થઈ રહ્યું છે?',
    'vivaad.why_matter': 'આ નિર્ણય કેમ મહત્ત્વનો છે?',
    'vivaad.read_more': 'વધુ વાંચો',
    'vivaad.read_less': 'ઓછું જુઓ',
    'vivaad.continue_views': 'અલગ અલગ મંતવ્યો જુઓ',
    'vivaad.exit': 'બહાર નીકળો',
    'vivaad.different_views_title': 'અલગ અલગ મંતવ્યો',
    'vivaad.different_views_desc': 'નિર્ણય લેતા પહેલા લોકોનું શું માનવું છે તે જુઓ.',
    'vivaad.ask_question': 'પ્રશ્ન પૂછો',
    'vivaad.close_question': 'બંધ કરો',
    'vivaad.type_question_placeholder': 'પ્રશ્ન પૂછો...',
    'vivaad.send': 'મોકલો',
    'vivaad.continue_choice': 'તમારો નિર્ણય પસંદ કરો',
    'vivaad.back': 'પાછળ',
    'vivaad.your_choice_title': 'તમે શું કરશો?',
    'vivaad.your_choice_desc': 'તમને સૌથી યોગ્ય લાગે તે વિકલ્પ પસંદ કરો.',
    'vivaad.continue_explain': 'કારણ સમજાવો',
    'vivaad.explain_title': 'તમે આ કેમ પસંદ કર્યું?',
    'vivaad.explain_desc': 'તમારા પોતાના શબ્દોમાં જણાવો.',
    'vivaad.explain_placeholder': 'તમારા શબ્દોમાં સમજાવો...',
    'vivaad.speak_btn': 'બોલીને જણાવો',
    'vivaad.listening': 'સાંભળી રહ્યા છીએ... (બોલો)',
    'vivaad.stop_listening': 'બંધ કરો',
    'vivaad.speech_not_supported': 'અવાજ ઇનપુટ ઉપલબ્ધ નથી. કૃપા કરીને ટાઇપ કરો.',
    'vivaad.submit_decision': 'નિર્ણય સબમિટ કરો',
    'vivaad.submitting': 'મૂલ્યાંકન થઈ રહ્યું છે...',
    'vivaad.feedback_title': 'તમારા નિર્ણયનું વિશ્લેષણ',
    'vivaad.your_decision': 'તમારો નિર્ણય',
    'vivaad.you_chose': 'તમે પસંદ કર્યું:',
    'vivaad.makes_sense': 'આ યોગ્ય છે કારણ કે...',
    'vivaad.think_about': 'આના પર પણ વિચાર કરો...',
    'vivaad.another_view': 'બીજો દ્રષ્ટિકોણ',
    'vivaad.see_details': 'વિગતવાર વિશ્લેષણ જુઓ',
    'vivaad.hide_details': 'છુપાવો',
    'vivaad.try_another': 'બીજો પ્રસંગ અજમાવો',
    'vivaad.try_again': 'ફરીથી પ્રયાસ કરો',
    'buddy.vivaad_help': 'મદદ જોઈએ છે?',
    'buddy.vivaad_explain_simple': 'સરળ શબ્દોમાં સમજાવી શકશો?',
    'buddy.vivaad_views_help': 'મંતવ્યો કેમ જુદા છે?',
    'buddy.vivaad_think_help': 'મારે શું વિચારવું જોઈએ?',
  },

  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'nav.learn': 'ಕಲಿಯಿರಿ',
    'nav.quiz': 'ಜ್ಞಾನ ಪರೀಕ್ಷೆ',
    'nav.vivaad': 'ನೀತಿ ವಿವಾದ',
    'nav.admin': 'ಆಡಳಿತ',
    'nav.explore_courses': 'ಕೋರ್ಸ್‌ಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    'nav.sign_in': 'ಸೈನ್ ಇನ್',
    'nav.sign_out': 'ಸೈನ್ ಔಟ್',
    'vivaad.badge': 'ನೀತಿ ವಿವಾದ',
    'vivaad.hero_title': 'ನೈಜ ನೀತಿ ನಿರ್ಧಾರಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ.',
    'vivaad.hero_sub': 'ಸನ್ನಿವೇಶವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ, ವಿಭಿನ್ನ ದೃಷ್ಟಿಕೋನಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನಿಮ್ಮದೇ ಆದ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಿ.',
    'vivaad.prompt_placeholder': 'ನೀವು ಪರಿಶೀಲಿಸಲು ಬಯಸುವ ನೀತಿ ವಿಷಯವನ್ನು ವಿವರಿಸಿ...',
    'vivaad.domain': 'ಕ್ಷೇತ್ರ',
    'vivaad.difficulty': 'ಮಟ್ಟ',
    'vivaad.scenario_type': 'ವಿಧ',
    'vivaad.upload_doc': 'ದಾಖಲೆ ಸೇರಿಸಿ',
    'vivaad.start_btn': 'ಪ್ರಾರಂಭಿಸಿ',
    'vivaad.generating': 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    'vivaad.card1_title': 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'vivaad.card1_desc': 'ವರದಿ ಅಥವಾ ನಿಯಮಾವಳಿಯಿಂದ ನಿರ್ಧಾರ ಸನ್ನಿವೇಶ ಸೃಷ್ಟಿಸಿ.',
    'vivaad.card1_btn': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'vivaad.card2_title': 'ಸನ್ನಿವೇಶ ಬರೆಯಿರಿ',
    'vivaad.card2_desc': 'ನಿಮ್ಮ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ಆಡಳಿತಾತ್ಮಕ ಸಮಸ್ಯೆಯನ್ನು ಬರೆಯಿರಿ.',
    'vivaad.card2_btn': 'ಪ್ರಾರಂಭಿಸಿ',
    'vivaad.card3_title': 'ಉದಾಹರಣೆಗಳನ್ನು ನೋಡಿ',
    'vivaad.card3_desc': 'ಸಿದ್ಧವಾಗಿರುವ ನೀತಿ ನಿರ್ಧಾರಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ.',
    'vivaad.card3_btn': 'ನೋಡಿ',
    'vivaad.try_section': 'ಒಂದು ಸನ್ನಿವೇಶವನ್ನು ಆರಿಸಿ',
    'vivaad.all': 'ಎಲ್ಲಾ',
    'vivaad.data_privacy': 'ಡೇಟಾ ಮತ್ತು ಗೌಪ್ಯತೆ',
    'vivaad.ai_gov': 'ಎಐ ಮತ್ತು ಆಡಳಿತ',
    'vivaad.public_health': 'ಸಾರ್ವಜನಿಕ ಆರೋಗ್ಯ',
    'vivaad.edu_policy': 'ಶಿಕ್ಷಣ ನೀತಿ',
    'vivaad.urban_dev': 'ನಗರಾಭಿವೃದ್ಧಿ',
    'vivaad.agriculture': 'ಕೃಷಿ',
    'step.1': '೧. ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ',
    'step.2': '೨. ವಿಭಿನ್ನ ಅಭಿಪ್ರಾಯಗಳು',
    'step.3': '೩. ನಿಮ್ಮ ಆಯ್ಕೆ',
    'step.4': '೪. ವಿವರಿಸಿ',
    'step.5': '೫. ಕಲಿಯಿರಿ',
    'vivaad.what_happening': 'ಏನು ನಡೆಯುತ್ತಿದೆ?',
    'vivaad.why_matter': 'ಇದು ಏಕೆ ಮುಖ್ಯ?',
    'vivaad.read_more': 'ಇನ್ನಷ್ಟು ಓದಿ',
    'vivaad.read_less': 'ಕಡಿಮೆ ಮಾಡಿ',
    'vivaad.continue_views': 'ವಿಭಿನ್ನ ಅಭಿಪ್ರಾಯಗಳನ್ನು ನೋಡಿ',
    'vivaad.exit': 'ನಿರ್ಗಮಿಸಿ',
    'vivaad.different_views_title': 'ವಿಭಿನ್ನ ಅಭಿಪ್ರಾಯಗಳು',
    'vivaad.different_views_desc': 'ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳುವ ಮುನ್ನ ಬೇರೆಯವರ ಅಭಿಪ್ರಾಯಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    'vivaad.ask_question': 'ಪ್ರಶ್ನೆ ಕೇಳಿ',
    'vivaad.close_question': 'ಮುಕ್ತಾಯಗೊಳಿಸಿ',
    'vivaad.type_question_placeholder': 'ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    'vivaad.send': 'ಕಳುಹಿಸಿ',
    'vivaad.continue_choice': 'ನಿಮ್ಮ ನಿರ್ಧಾರ ಆಯ್ಕೆಮಾಡಿ',
    'vivaad.back': 'ಹಿಂದಕ್ಕೆ',
    'vivaad.your_choice_title': 'ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?',
    'vivaad.your_choice_desc': 'ನಿಮಗೆ ಸೂಕ್ತವೆನಿಸುವ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿಕೊಳ್ಳಿ.',
    'vivaad.continue_explain': 'ಕಾರಣ ವಿವರಿಸಿ',
    'vivaad.explain_title': 'ನೀವು ಇದನ್ನು ಏಕೆ ಆರಿಸಿದ್ದೀರಿ?',
    'vivaad.explain_desc': 'ನಿಮ್ಮ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ತಿಳಿಸಿ.',
    'vivaad.explain_placeholder': 'ನಿಮ್ಮ ಮಾತುಗಳಲ್ಲಿ ವಿವರಿಸಿ...',
    'vivaad.speak_btn': 'ಮಾತನಾಡಿ ಹೇಳಿ',
    'vivaad.listening': 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ... (ಮಾತನಾಡಿ)',
    'vivaad.stop_listening': 'ನಿಲ್ಲಿಸಿ',
    'vivaad.speech_not_supported': 'ಧ್ವನಿ ಇನ್ಪುಟ್ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ. ದಯವಿಟ್ಟು ಟೈಪ್ ಮಾಡಿ.',
    'vivaad.submit_decision': 'ನಿರ್ಧಾರ ಸಲ್ಲಿಸಿ',
    'vivaad.submitting': 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'vivaad.feedback_title': 'ನಿಮ್ಮ ನಿರ್ಧಾರದ ವಿಶ್ಲೇಷಣೆ',
    'vivaad.your_decision': 'ನಿಮ್ಮ ನಿರ್ಧಾರ',
    'vivaad.you_chose': 'ನೀವು ಆರಿಸಿದ್ದು:',
    'vivaad.makes_sense': 'ಇದು ಸಮಂಜಸವಾಗಿದೆ ಏಕೆಂದರೆ...',
    'vivaad.think_about': 'ಇದನ್ನೂ ಯೋಚಿಸಿ...',
    'vivaad.another_view': 'ಮತ್ತೊಂದು ದೃಷ್ಟಿಕೋನ',
    'vivaad.see_details': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    'vivaad.hide_details': 'ಮರೆಮಾಡಿ',
    'vivaad.try_another': 'ಮತ್ತೊಂದನ್ನು ಪ್ರಯತ್ನಿಸಿ',
    'vivaad.try_again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'buddy.vivaad_help': 'ಸಹಾಯ ಬೇಕೇ?',
    'buddy.vivaad_explain_simple': 'ಸರಳವಾಗಿ ವಿವರಿಸಬಲ್ಲಿರಾ?',
    'buddy.vivaad_views_help': 'ಅಭಿಪ್ರಾಯಗಳು ಏಕೆ ಭಿನ್ನವಾಗಿವೆ?',
    'buddy.vivaad_think_help': 'ನಾನು ಏನನ್ನು ಯೋಚಿಸಬೇಕು?',
  },

  ml: {
    'nav.home': 'ഹോം',
    'nav.profile': 'എന്റെ പ്രൊഫൈൽ',
    'nav.learn': 'പഠിക്കുക',
    'nav.quiz': 'വിജ്ഞാന പരീക്ഷ',
    'nav.vivaad': 'നീതി വിവാദ്',
    'nav.admin': 'ഭരണനിർവ്വഹണം',
    'nav.explore_courses': 'കോഴ്സുകൾ കാണുക',
    'nav.sign_in': 'സൈൻ ഇൻ',
    'nav.sign_out': 'സൈൻ ഔട്ട്',
    'vivaad.badge': 'നീതി വിവാദ്',
    'vivaad.hero_title': 'യഥാർത്ഥ നയ തീരുമാനങ്ങൾ പരിശീലിക്കുക.',
    'vivaad.hero_sub': 'സാഹചര്യം മനസ്സിലാക്കുക, വ്യത്യസ്ത കാഴ്ചപ്പാടുകൾ പരിശോധിക്കുക, സ്വന്തം തീരുമാനമെടുക്കുക.',
    'vivaad.prompt_placeholder': 'നിങ്ങൾ പരിശോധിക്കാൻ ആഗ്രഹിക്കുന്ന നയപരമായ വിഷയം എഴുതുക...',
    'vivaad.domain': 'മേഖല',
    'vivaad.difficulty': 'നിലവാരം',
    'vivaad.scenario_type': 'തരം',
    'vivaad.upload_doc': 'ഡോക്യുമെന്റ് അപ്‌ലോഡ്',
    'vivaad.start_btn': 'ആരംഭിക്കുക',
    'vivaad.generating': 'തയ്യാറാക്കുന്നു...',
    'vivaad.card1_title': 'ഡോക്യുമെന്റ് അപ്‌ലോഡ് ചെയ്യുക',
    'vivaad.card1_desc': 'ഔദ്യോഗിക റിപ്പോർട്ടിൽ നിന്ന് തീരുമാനം പരിശീലിക്കുക.',
    'vivaad.card1_btn': 'അപ്‌ലോഡ്',
    'vivaad.card2_title': 'സാഹചര്യം എഴുതുക',
    'vivaad.card2_desc': 'നിങ്ങളുടെ സ്വന്തം വാക്കുകളിൽ പ്രശ്നം രേഖപ്പെടുത്തുക.',
    'vivaad.card2_btn': 'തുടങ്ങുക',
    'vivaad.card3_title': 'ഉദാഹരണങ്ങൾ കാണുക',
    'vivaad.card3_desc': 'പ്രധാന മേഖലകളിലെ തീരുമാന സാഹചര്യങ്ങൾ പരിശോധിക്കുക.',
    'vivaad.card3_btn': 'കാണുക',
    'vivaad.try_section': 'ഒരു സാഹചര്യം തിരഞ്ഞെടുക്കുക',
    'vivaad.all': 'എല്ലാം',
    'vivaad.data_privacy': 'വിവരങ്ങളും സ്വകാര്യതയും',
    'vivaad.ai_gov': 'എഐ & ഭരണം',
    'vivaad.public_health': 'പൊതുജനാരോഗ്യം',
    'vivaad.edu_policy': 'വിദ്യാഭ്യാസ നയം',
    'vivaad.urban_dev': 'നഗര വികസനം',
    'vivaad.agriculture': 'കൃഷി',
    'step.1': '1. മനസ്സിലാക്കുക',
    'step.2': '2. വ്യത്യസ്ത കാഴ്ചപ്പാടുകൾ',
    'step.3': '3. നിങ്ങളുടെ തീരുമാനം',
    'step.4': '4. വിശദീകരിക്കുക',
    'step.5': '5. പഠിക്കുക',
    'vivaad.what_happening': 'എന്താണ് സംഭവിക്കുന്നത്?',
    'vivaad.why_matter': 'ഇത് എന്തുകൊണ്ട് പ്രധാനമാണ്?',
    'vivaad.read_more': 'കൂടുതൽ വായിക്കുക',
    'vivaad.read_less': 'ചുരുക്കുക',
    'vivaad.continue_views': 'വ്യത്യസ്ത കാഴ്ചപ്പാടുകൾ കാണുക',
    'vivaad.exit': 'പുറത്തു കടക്കുക',
    'vivaad.different_views_title': 'വ്യത്യസ്ത കാഴ്ചപ്പാടുകൾ',
    'vivaad.different_views_desc': 'തീരുമാനമെടുക്കുന്നതിന് മുൻപ് മറ്റുള്ളവരുടെ അഭിപ്രായങ്ങൾ അറിയുക.',
    'vivaad.ask_question': 'ചോദ്യം ചോദിക്കുക',
    'vivaad.close_question': 'അവസാനിപ്പിക്കുക',
    'vivaad.type_question_placeholder': 'ചോദ്യം ചോദിക്കുക...',
    'vivaad.send': 'അയക്കുക',
    'vivaad.continue_choice': 'തീരുമാനം തിരഞ്ഞെടുക്കുക',
    'vivaad.back': 'തിരികെ',
    'vivaad.your_choice_title': 'നിങ്ങൾ എന്ത് ചെയ്യും?',
    'vivaad.your_choice_desc': 'ഏറ്റവും അനുയോജ്യമെന്ന് തോന്നുന്ന ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക.',
    'vivaad.continue_explain': 'വിശദീകരിക്കുക',
    'vivaad.explain_title': 'എന്തുകൊണ്ട് ഇത് തിരഞ്ഞെടുത്തു?',
    'vivaad.explain_desc': 'നിങ്ങളുടെ സ്വന്തം വാക്കുകളിൽ പറയുക.',
    'vivaad.explain_placeholder': 'സ്വന്തം വാക്കുകളിൽ വിശദീകരിക്കുക...',
    'vivaad.speak_btn': 'സംസാരിച്ച് പറയുക',
    'vivaad.listening': 'കേൾക്കുന്നു... (സംസാരിക്കുക)',
    'vivaad.stop_listening': 'നിർത്തുക',
    'vivaad.speech_not_supported': 'വോയ്സ് ഇൻപുട്ട് ലഭ്യമല്ല. ടൈപ്പ് ചെയ്യുക.',
    'vivaad.submit_decision': 'തീരുമാനം സമർപ്പിക്കുക',
    'vivaad.submitting': 'വിലയിരുത്തുന്നു...',
    'vivaad.feedback_title': 'നിങ്ങളുടെ തീരുമാനത്തിന്റെ വിലയിരുത്തൽ',
    'vivaad.your_decision': 'നിങ്ങളുടെ തീരുമാനം',
    'vivaad.you_chose': 'നിങ്ങൾ തിരഞ്ഞെടുത്തത്:',
    'vivaad.makes_sense': 'ഇത് യുക്തിസഹമാണ് കാരണം...',
    'vivaad.think_about': 'ഇതും ചിന്തിക്കുക...',
    'vivaad.another_view': 'മറ്റൊരു കാഴ്ചപ്പാട്',
    'vivaad.see_details': 'വിശദാംശങ്ങൾ കാണുക',
    'vivaad.hide_details': 'മറയ്ക്കുക',
    'vivaad.try_another': 'മറ്റൊന്ന് ശ്രമിക്കുക',
    'vivaad.try_again': 'വീണ്ടും ശ്രമിക്കുക',
    'buddy.vivaad_help': 'സഹായം വേണോ?',
    'buddy.vivaad_explain_simple': 'ലളിതമായി വിശദീകരിക്കാമോ?',
    'buddy.vivaad_views_help': 'അഭിപ്രായ വ്യത്യാസം എന്തുകൊണ്ട്?',
    'buddy.vivaad_think_help': 'ഞാൻ എന്താണ് ചിന്തിക്കേണ്ടത്?',
  },

  pa: {
    'nav.home': 'ਮੁੱਖ ਪੰਨਾ',
    'nav.profile': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    'nav.learn': 'ਸਿੱਖੋ',
    'nav.quiz': 'ਗਿਆਨ ਪਰਖ',
    'nav.vivaad': 'ਨੀਤੀ ਵਿਵਾਦ',
    'nav.admin': 'ਪ੍ਰਸ਼ਾਸਨ',
    'nav.explore_courses': 'ਕੋਰਸ ਦੇਖੋ',
    'nav.sign_in': 'ਸਾਈਨ ਇਨ',
    'nav.sign_out': 'ਸਾਈਨ ਆਉਟ',
    'vivaad.badge': 'ਨੀਤੀ ਵਿਵਾਦ',
    'vivaad.hero_title': 'ਅਸਲ ਨੀਤੀਗਤ ਫੈਸਲਿਆਂ ਦਾ ਅਭਿਆਸ ਕਰੋ।',
    'vivaad.hero_sub': 'ਸਥਿਤੀ ਨੂੰ ਸਮਝੋ, ਵੱਖ-ਵੱਖ ਨਜ਼ਰੀਏ ਦੇਖੋ, ਅਤੇ ਆਪਣਾ ਫੈਸਲਾ ਲਓ।',
    'vivaad.prompt_placeholder': 'ਉਹ ਨੀਤੀਗਤ ਮੁੱਦਾ ਲਿਖੋ ਜਿਸ ਬਾਰੇ ਤੁਸੀਂ ਵਿਚਾਰ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ...',
    'vivaad.domain': 'ਖੇਤਰ',
    'vivaad.difficulty': 'ਪੱਧਰ',
    'vivaad.scenario_type': 'ਕਿਸਮ',
    'vivaad.upload_doc': 'ਦਸਤਾਵੇਜ਼ ਜੋੜੋ',
    'vivaad.start_btn': 'ਸ਼ੁਰੂ ਕਰੋ',
    'vivaad.generating': 'ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ...',
    'vivaad.card1_title': 'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ',
    'vivaad.card1_desc': 'ਰਿਪੋਰਟ ਜਾਂ ਨਿਯਮਾਂ ਤੋਂ ਫੈਸਲੇ ਦੀ ਸਥਿਤੀ ਬਣਾਓ।',
    'vivaad.card1_btn': 'ਅਪਲੋਡ ਕਰੋ',
    'vivaad.card2_title': 'ਸਥਿਤੀ ਲਿਖੋ',
    'vivaad.card2_desc': 'ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਪ੍ਰਸ਼ਾਸਨਿਕ ਮੁੱਦਾ ਲਿਖੋ।',
    'vivaad.card2_btn': 'ਸ਼ੁਰੂ ਕਰੋ',
    'vivaad.card3_title': 'ਉਦਾਹਰਣਾਂ ਦੇਖੋ',
    'vivaad.card3_desc': 'ਤਿਆਰ ਨੀਤੀਗਤ ਫੈਸਲਿਆਂ ਦਾ ਅਭਿਆਸ ਕਰੋ।',
    'vivaad.card3_btn': 'ਦੇਖੋ',
    'vivaad.try_section': 'ਇੱਕ ਸਥਿਤੀ ਚੁਣੋ',
    'vivaad.all': 'ਸਾਰੇ',
    'vivaad.data_privacy': 'ਡਾਟਾ ਅਤੇ ਨਿੱਜਤਾ',
    'vivaad.ai_gov': 'ਏਆਈ ਅਤੇ ਸ਼ਾਸਨ',
    'vivaad.public_health': 'ਸਿਹਤ',
    'vivaad.edu_policy': 'ਸਿੱਖਿਆ ਨੀਤੀ',
    'vivaad.urban_dev': 'ਸ਼ਹਿਰੀ ਵਿਕਾਸ',
    'vivaad.agriculture': 'ਖੇਤੀਬਾੜੀ',
    'step.1': '1. ਸਮਝੋ',
    'step.2': '2. ਵੱਖ-ਵੱਖ ਵਿਚਾਰ',
    'step.3': '3. ਤੁਹਾਡੀ ਚੋਣ',
    'step.4': '4. ਕਾਰਨ ਦੱਸੋ',
    'step.5': '5. ਸਿੱਖੋ',
    'vivaad.what_happening': 'ਕੀ ਹੋ ਰਿਹਾ ਹੈ?',
    'vivaad.why_matter': 'ਇਹ ਕਿਉਂ ਮਹੱਤਵਪੂਰਨ ਹੈ?',
    'vivaad.read_more': 'ਹੋਰ ਪੜ੍ਹੋ',
    'vivaad.read_less': 'ਘੱਟ ਦੇਖੋ',
    'vivaad.continue_views': 'ਵੱਖ-ਵੱਖ ਵਿਚਾਰ ਦੇਖੋ',
    'vivaad.exit': 'ਬਾਹਰ ਨਿਕਲੋ',
    'vivaad.different_views_title': 'ਵੱਖ-ਵੱਖ ਵਿਚਾਰ',
    'vivaad.different_views_desc': 'ਫੈਸਲਾ ਲੈਣ ਤੋਂ ਪਹਿਲਾਂ ਦੇਖੋ ਕਿ ਲੋਕ ਕੀ ਸੋਚਦੇ ਹਨ।',
    'vivaad.ask_question': 'ਸਵਾਲ ਪੁੱਛੋ',
    'vivaad.close_question': 'ਬੰਦ ਕਰੋ',
    'vivaad.type_question_placeholder': 'ਸਵਾਲ ਪੁੱਛੋ...',
    'vivaad.send': 'ਭੇਜੋ',
    'vivaad.continue_choice': 'ਆਪਣਾ ਫੈਸਲਾ ਚੁਣੋ',
    'vivaad.back': 'ਪਿੱਛੇ',
    'vivaad.your_choice_title': 'ਤੁਸੀਂ ਕੀ ਕਰੋਗੇ?',
    'vivaad.your_choice_desc': 'ਜੋ ਬਿਹਤਰ ਲੱਗੇ ਉਹ ਚੁਣੋ।',
    'vivaad.continue_explain': 'ਕਾਰਨ ਦੱਸੋ',
    'vivaad.explain_title': 'ਤੁਸੀਂ ਇਹ ਕਿਉਂ ਚੁਣਿਆ?',
    'vivaad.explain_desc': 'ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੋ।',
    'vivaad.explain_placeholder': 'ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੋ...',
    'vivaad.speak_btn': 'ਬੋਲ ਕੇ ਦੱਸੋ',
    'vivaad.listening': 'ਸੁਣ ਰਹੇ ਹਾਂ... (ਬੋਲੋ)',
    'vivaad.stop_listening': 'ਰੋਕੋ',
    'vivaad.speech_not_supported': 'ਆਵਾਜ਼ ਸਹਿਯੋਗੀ ਨਹੀਂ ਹੈ। ਟਾਈਪ ਕਰੋ।',
    'vivaad.submit_decision': 'ਫੈਸਲਾ ਜਮ੍ਹਾਂ ਕਰੋ',
    'vivaad.submitting': 'ਮੁਲਾਂਕਣ ਹੋ ਰਿਹਾ ਹੈ...',
    'vivaad.feedback_title': 'ਤੁਹਾਡੇ ਫੈਸਲੇ ਦਾ ਮੁਲਾਂਕਣ',
    'vivaad.your_decision': 'ਤੁਹਾਡਾ ਫੈਸਲਾ',
    'vivaad.you_chose': 'ਤੁਸੀਂ ਚੁਣਿਆ:',
    'vivaad.makes_sense': 'ਇਹ ਠੀਕ ਲੱਗਦਾ ਹੈ ਕਿਉਂਕਿ...',
    'vivaad.think_about': 'ਇਸ ਬਾਰੇ ਵੀ ਸੋਚੋ...',
    'vivaad.another_view': 'ਦੂਜਾ ਨਜ਼ਰੀਆ',
    'vivaad.see_details': 'ਵੇਰਵੇ ਦੇਖੋ',
    'vivaad.hide_details': 'ਛੁਪਾਓ',
    'vivaad.try_another': 'ਹੋਰ ਅਜ਼ਮਾਓ',
    'vivaad.try_again': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'buddy.vivaad_help': 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    'buddy.vivaad_explain_simple': 'ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਸਮਝਾਓ?',
    'buddy.vivaad_views_help': 'ਵਿਚਾਰ ਵੱਖਰੇ ਕਿਉਂ ਹਨ?',
    'buddy.vivaad_think_help': 'ਮੈਨੂੰ ਕੀ ਸੋਚਣਾ ਚਾਹੀਦਾ ਹੈ?',
  },

  or: {
    'nav.home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    'nav.profile': 'ମୋ ପ୍ରୋଫାଇଲ୍',
    'nav.learn': 'ଶିଖନ୍ତୁ',
    'nav.quiz': 'ଜ୍ଞାନ ପରୀକ୍ଷା',
    'nav.vivaad': 'ନୀତି ବିବାଦ',
    'nav.admin': 'ପ୍ରଶାସନ',
    'nav.explore_courses': 'କୋର୍ସ ଦେଖନ୍ତୁ',
    'nav.sign_in': 'ସାଇନ୍ ଇନ୍',
    'nav.sign_out': 'ଲଗ୍ ଆଉଟ୍',
    'vivaad.badge': 'ନୀତି ବିବାଦ',
    'vivaad.hero_title': 'ବାସ୍ତବିକ ନୀତିଗତ ନିଷ୍ପତ୍ତି ଅଭ୍ୟାସ କରନ୍ତୁ।',
    'vivaad.hero_sub': 'ପରିସ୍ଥିତିକୁ ବୁଝନ୍ତୁ, ବିଭିନ୍ନ ଦୃଷ୍ଟିକୋଣ ଦେଖନ୍ତୁ ଏବଂ ନିଜ ନିଷ୍ପତ୍ତି ନିଅନ୍ତୁ।',
    'vivaad.prompt_placeholder': 'ଆପଣ ଯେଉଁ ନୀତିଗତ ବିଷୟ ବିଚାର କରିବାକୁ ଚାହାଁନ୍ତି ତାହା ଲେଖନ୍ତୁ...',
    'vivaad.domain': 'କ୍ଷେତ୍ର',
    'vivaad.difficulty': 'ସ୍ତର',
    'vivaad.scenario_type': 'ପ୍ରକାର',
    'vivaad.upload_doc': 'ଦସ୍ତାବିଜ୍ ଯୋଡ଼ନ୍ତୁ',
    'vivaad.start_btn': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'vivaad.generating': 'ପ୍ରସ୍ତୁତ ହେଉଛି...',
    'vivaad.card1_title': 'ଦସ୍ତାବିଜ୍ ଅପଲୋଡ୍ କରନ୍ତୁ',
    'vivaad.card1_desc': 'ନିର୍ଦ୍ଦେଶାବଳୀ କିମ୍ବା ରିପୋର୍ଟରୁ ନିଷ୍ପତ୍ତି ସ୍ଥିତି ସୃଷ୍ଟି କରନ୍ତୁ।',
    'vivaad.card1_btn': 'ଅପଲୋଡ୍',
    'vivaad.card2_title': 'ସ୍ଥିତି ଲେଖନ୍ତୁ',
    'vivaad.card2_desc': 'ନିଜ ଭାଷାରେ ପ୍ରଶାସନିକ ସମସ୍ୟା ଲେଖନ୍ତୁ।',
    'vivaad.card2_btn': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'vivaad.card3_title': 'ଉଦାହରଣ ଦେଖନ୍ତୁ',
    'vivaad.card3_desc': 'ବିଭିନ୍ନ କ୍ଷେତ୍ରର ନୀତିଗତ ନିଷ୍ପତ୍ତି ଅଭ୍ୟାସ କରନ୍ତୁ।',
    'vivaad.card3_btn': 'ଦେଖନ୍ତୁ',
    'vivaad.try_section': 'ଗୋଟିଏ ସ୍ଥିତି ବାଛନ୍ତୁ',
    'vivaad.all': 'ସମସ୍ତ',
    'vivaad.data_privacy': 'ତଥ୍ୟ ଓ ଗୋପନୀୟତା',
    'vivaad.ai_gov': 'ଏଆଇ ଓ ପ୍ରଶାସନ',
    'vivaad.public_health': 'ଜନସ୍ୱାସ୍ଥ୍ୟ',
    'vivaad.edu_policy': 'ଶିକ୍ଷା ନୀତି',
    'vivaad.urban_dev': 'ସହର ଉନ୍ନୟନ',
    'vivaad.agriculture': 'କୃଷି',
    'step.1': '୧. ବୁଝନ୍ତୁ',
    'step.2': '୨. ବିଭିନ୍ନ ମତ',
    'step.3': '୩. ଆପଣଙ୍କ ପସନ୍ଦ',
    'step.4': '୪. କାରଣ ବୁଝାନ୍ତୁ',
    'step.5': '୫. ଶିଖନ୍ତୁ',
    'vivaad.what_happening': 'କ’ଣ ଘଟୁଛି?',
    'vivaad.why_matter': 'ଏହା କାହିଁକି ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ?',
    'vivaad.read_more': 'ଅଧିକ ପଢ଼ନ୍ତୁ',
    'vivaad.read_less': 'କମ୍ ଦେଖନ୍ତୁ',
    'vivaad.continue_views': 'ବିଭିନ୍ନ ମତ ଦେଖନ୍ତୁ',
    'vivaad.exit': 'ବାହାରକୁ ଯାଆନ୍ତୁ',
    'vivaad.different_views_title': 'ବିଭିନ୍ନ ମତ',
    'vivaad.different_views_desc': 'ନିଷ୍ପତ୍ତି ନେବା ପୂର୍ବରୁ ଅନ୍ୟମାନଙ୍କ ମତ ଦେଖନ୍ତୁ।',
    'vivaad.ask_question': 'ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ',
    'vivaad.close_question': 'ବନ୍ଦ କରନ୍ତୁ',
    'vivaad.type_question_placeholder': 'ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ...',
    'vivaad.send': 'ପଠାନ୍ତୁ',
    'vivaad.continue_choice': 'ଆପଣଙ୍କ ନିଷ୍ପତ୍ତି ବାଛନ୍ତୁ',
    'vivaad.back': 'ପଛକୁ',
    'vivaad.your_choice_title': 'ଆପଣ କ’ଣ କରିବେ?',
    'vivaad.your_choice_desc': 'ଆପଣଙ୍କୁ ଯାହା ଉପଯୁକ୍ତ ଲାଗୁଛି ତାହା ବାଛନ୍ତୁ।',
    'vivaad.continue_explain': 'କାରଣ ବୁଝାନ୍ତୁ',
    'vivaad.explain_title': 'ଆପଣ ଏହା କାହିଁକି ବାଛିଲେ?',
    'vivaad.explain_desc': 'ନିଜ ଭାଷାରେ କୁହନ୍ତୁ।',
    'vivaad.explain_placeholder': 'ନିଜ ଶବ୍ଦରେ ବୁଝାନ୍ତୁ...',
    'vivaad.speak_btn': 'କହିକି ବୁଝାନ୍ତୁ',
    'vivaad.listening': 'ଶୁଣୁଛୁ... (କୁହନ୍ତୁ)',
    'vivaad.stop_listening': 'ବନ୍ଦ କରନ୍ତୁ',
    'vivaad.speech_not_supported': 'ଭଏସ୍ ସମର୍ଥିତ ନୁହେଁ। ଟାଇପ୍ କରନ୍ତୁ।',
    'vivaad.submit_decision': 'ନିଷ୍ପତ୍ତି ଦାଖଲ କରନ୍ତୁ',
    'vivaad.submitting': 'ମୂଲ୍ୟାଙ୍କନ ଚାଲିଛି...',
    'vivaad.feedback_title': 'ଆପଣଙ୍କ ନିଷ୍ପତ୍ତିର ବିଶ୍ଳେଷଣ',
    'vivaad.your_decision': 'ଆପଣଙ୍କ ନିଷ୍ପତ୍ତି',
    'vivaad.you_chose': 'ଆପଣ ବାଛିଛନ୍ତି:',
    'vivaad.makes_sense': 'ଏହା ଯଥାର୍ଥ କାରଣ...',
    'vivaad.think_about': 'ଏହା ଉପରେ ମଧ୍ୟ ଚିନ୍ତା କରନ୍ତୁ...',
    'vivaad.another_view': 'ଅନ୍ୟ ଏକ ଦୃଷ୍ଟିକୋଣ',
    'vivaad.see_details': 'ବିସ୍ତୃତ ବିବରଣୀ ଦେଖନ୍ତୁ',
    'vivaad.hide_details': 'ଲୁଚାନ୍ତୁ',
    'vivaad.try_another': 'ଅନ୍ୟ ଏକ ଚେଷ୍ଟା କରନ୍ତୁ',
    'vivaad.try_again': 'ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ',
    'buddy.vivaad_help': 'ସାହାଯ୍ୟ ଦରକାର କି?',
    'buddy.vivaad_explain_simple': 'ସହଜରେ ବୁଝାଇପାରିବେ କି?',
    'buddy.vivaad_views_help': 'ମତରେ ଭିନ୍ନତା କାହିଁକି?',
    'buddy.vivaad_think_help': 'ମୁଁ କ’ଣ ଭାବିବା ଉଚିତ୍?',
  }
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  currentLanguageOption: LanguageOption;
  t: (key: string, fallback?: string) => string;
  speechCode: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>('en');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('neeti_saarthi_lang') as SupportedLanguage | null;
      if (saved && SUPPORTED_LANGUAGES.some(l => l.code === saved)) {
        setLanguageState(saved);
      }
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('neeti_saarthi_lang', lang);
      window.dispatchEvent(new CustomEvent('neetiLanguageChange', { detail: { language: lang } }));
    }
  };

  const currentLanguageOption = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];

  const t = (key: string, fallback?: string): string => {
    const langDict = DICTIONARY[language] || DICTIONARY['en'];
    if (langDict[key]) return langDict[key];
    const enDict = DICTIONARY['en'];
    if (enDict[key]) return enDict[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguageOption,
        t,
        speechCode: currentLanguageOption.speechCode,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Graceful fallback for components outside provider
    const fallbackOption = SUPPORTED_LANGUAGES[0];
    return {
      language: 'en',
      setLanguage: () => {},
      currentLanguageOption: fallbackOption,
      t: (key: string, fallback?: string) => DICTIONARY['en'][key] || fallback || key,
      speechCode: 'en-IN',
    };
  }
  return context;
};
