# Generated by Django 6.1 on 2026-09-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
        ('core', '0002_user_baseline_completed_user_learning_preferences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BaselineAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('calculated_ctq', models.FloatField(default=0.0)),
                ('domain_scores', models.JSONField(default=dict)),
                ('detailed_answers', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaselineQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list, help_text='List of string options')),
                ('correct_option_index', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_questions', to='core.competencydomain')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_questions', to='core.subskill')),
            ],
        ),
    ]
