# Generated by Django 6.1 on 2026-09-13 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_quizattempt_user_baselineassessmentattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.AddField(
            model_name='documentupload',
            name='chunks',
            field=models.JSONField(default=list, help_text='List of structured chunks: [{chunk_id, page_number, section_title, text}]'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='file_type',
            field=models.CharField(default='PDF', max_length=20),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='page_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by_ai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='evidence_text',
            field=models.TextField(blank=True, default='', help_text='Exact continuous excerpt supporting question and answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TRUE_FALSE', 'True / False'), ('SCENARIO', 'Scenario'), ('SHORT_ANSWER', 'Short Answer')], default='MCQ', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='source_chunk_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='source_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='source_section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_estimate_mins',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, default='')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='assessment.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.option')),
            ],
        ),
    ]
