# Generated by Django 6.1 on 2026-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_question_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_source_question',
            field=models.BooleanField(default=False, help_text='Preserved directly from the source training material'),
        ),
        migrations.AddField(
            model_name='question',
            name='provenance_metadata',
            field=models.JSONField(default=dict, help_text='Detailed audit trail: source_doc, page, section, chunk_id, evidence, competency, model, version'),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_status',
            field=models.CharField(choices=[('VALIDATED', 'Validated'), ('PENDING_REVIEW', 'Pending Admin Review'), ('REJECTED', 'Rejected')], default='VALIDATED', max_length=20),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='misconception_tag',
            field=models.CharField(blank=True, default='', help_text='Concept confused or missed', max_length=255),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='pedagogical_explanation',
            field=models.TextField(blank=True, default='', help_text='Diagnostic explanation teaching the underlying principle with example'),
        ),
    ]
