# Generated by Django 6.1 on 2026-08-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igot_course_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(default='iGOT Karmayogi / MoSPI', max_length=150)),
                ('description', models.TextField()),
                ('duration_hours', models.FloatField(default=4.0)),
                ('difficulty', models.CharField(default='Intermediate', max_length=50)),
                ('url', models.URLField(default='https://igotkarmayogi.gov.in/')),
                ('rating', models.FloatField(default=4.8)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.competencydomain')),
                ('target_subskills', models.ManyToManyField(related_name='courses', to='core.subskill')),
            ],
        ),
    ]
