# Generated by Django 6.1 on 2026-09-13 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_buddy_language_user_buddy_voice_enabled_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='competencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='3 Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='last_synced_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(default='igot', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Official iGOT course thumbnail URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='igot_course_id',
            field=models.CharField(help_text='Canonical iGOT content identifier (e.g. do_11382449019283865611)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(default='iGOT Karmayogi', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_subskills',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.subskill'),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(default='https://igotkarmayogi.gov.in/', max_length=500),
        ),
    ]
