# Generated by Django 6.1 on 2026-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_buddy_language_user_buddy_voice_enabled_and_more'),
        ('courses', '0002_course_category_course_competencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='igot_course_url',
            field=models.URLField(blank=True, help_text='Verified official individual iGOT course URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='url_status',
            field=models.CharField(default='verified', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='url_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='igot_course_id',
            field=models.CharField(db_index=True, help_text='Canonical iGOT content identifier (e.g. do_1136364937253437441916)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(db_index=True, default='iGOT Karmayogi', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='source',
            field=models.CharField(db_index=True, default='igot', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(default='https://portal.igotkarmayogi.gov.in/', max_length=500),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'category'], name='courses_cou_status_7df71c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'source'], name='courses_cou_status_ef60a6_idx'),
        ),
    ]
