# Generated by Django 6.1 on 2026-09-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_igotcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, help_text='Official lastUpdatedOn timestamp from iGOT', null=True),
        ),
    ]
