# Generated by Django 6.1 on 2026-08-23 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('round_name', models.CharField(default='Opening Arguments', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='DebateScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Data Policy', max_length=100)),
                ('description', models.TextField()),
                ('initial_constraint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_code', models.CharField(max_length=50, unique=True)),
                ('publisher', models.CharField(default='MoSPI / National Statistical Commission', max_length=150)),
                ('content', models.TextField()),
                ('publication_year', models.IntegerField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name='AgentArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=20)),
                ('agent_name', models.CharField(max_length=100)),
                ('avatar_color', models.CharField(default='blue', max_length=30)),
                ('priority_tag', models.CharField(max_length=100)),
                ('argument_text', models.TextField()),
                ('source_citation', models.TextField(help_text='Retrieved MoSPI document citation')),
                ('document_code', models.CharField(blank=True, max_length=50, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='debate.debateround')),
            ],
        ),
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_constraint', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.debatescenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='debateround',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='debate.debatesession'),
        ),
        migrations.CreateModel(
            name='DecisionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('recommended_policy', models.TextField()),
                ('tradeoffs_identified', models.JSONField(default=list)),
                ('mitigation_steps', models.JSONField(default=list)),
                ('judgment_tree', models.JSONField(default=dict, help_text='Expandable tree mapping claims to MoSPI sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_report', to='debate.debatesession')),
            ],
        ),
        migrations.CreateModel(
            name='FallacyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('target_agent_name', models.CharField(max_length=100)),
                ('argument_snippet', models.TextField()),
                ('fallacy_type', models.CharField(max_length=100)),
                ('options', models.JSONField(default=list)),
                ('correct_option_index', models.IntegerField(default=0)),
                ('explanation', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('user_answered_index', models.IntegerField(blank=True, null=True)),
                ('is_user_correct', models.BooleanField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallacies', to='debate.debatesession')),
            ],
        ),
    ]
