# Generated by Django 5.0.14 on 2026-08-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatescenario',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=30),
        ),
        migrations.AddField(
            model_name='debatescenario',
            name='learning_objective',
            field=models.TextField(blank=True, default='Evaluate data collection policy trade-offs and ensure data privacy compliance.', null=True),
        ),
        migrations.AddField(
            model_name='debatescenario',
            name='reference_sources',
            field=models.ManyToManyField(blank=True, related_name='scenarios', to='debate.referencedocument'),
        ),
        migrations.AddField(
            model_name='debatescenario',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=30),
        ),
        migrations.AddField(
            model_name='debatescenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='document_type',
            field=models.CharField(default='Official Policy Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='page_reference',
            field=models.CharField(default='Section 4.2', max_length=100),
        ),
        migrations.CreateModel(
            name='ScenarioConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True, null=True)),
                ('trigger_round', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='debate.debatescenario')),
            ],
        ),
    ]
