# Generated by Django 6.1 on 2026-09-13 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_buddy_language_user_buddy_voice_enabled_and_more'),
        ('debate', '0002_debatescenario_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaadScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('DOCUMENT', 'Based on Provided Material'), ('CUSTOM', 'Creator-Provided Scenario')], default='CUSTOM', max_length=20)),
                ('category', models.CharField(default='Data Policy', max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('version', models.IntegerField(default=1)),
                ('situation', models.TextField(help_text='Detailed public-sector administrative situation')),
                ('decision_question', models.TextField(help_text='The core policy dilemma the learner must decide')),
                ('objective', models.TextField(blank=True, default='', help_text='Policy or public interest goal')),
                ('constraints', models.JSONField(default=list, help_text='List of constraints: legal, fiscal, operational, time')),
                ('affected_people', models.JSONField(default=list, help_text='Affected citizen groups, enumerators, departments')),
                ('risks', models.JSONField(default=list, help_text='Operational, public trust, and legal risks')),
                ('options', models.JSONField(default=list, help_text='List of decision options: [{id, label, summary}]')),
                ('evaluation_criteria', models.JSONField(default=list, help_text='List of evaluation dimensions')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_scenarios', to=settings.AUTH_USER_MODEL)),
                ('target_subskills', models.ManyToManyField(blank=True, related_name='vivaad_scenarios', to='core.subskill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VivaadPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=150)),
                ('avatar_color', models.CharField(default='emerald', max_length=30)),
                ('primary_concern', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('position', models.TextField(help_text='Opening position statement and stance')),
                ('relevant_evidence', models.TextField(blank=True, default='')),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('source_section', models.CharField(blank=True, default='', max_length=255)),
                ('key_questions', models.JSONField(default=list, help_text='Challenge questions raised by this perspective')),
                ('order', models.IntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectives', to='debate.vivaadscenario')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VivaadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DECIDED', 'Decided'), ('EVALUATED', 'Evaluated')], default='IN_PROGRESS', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active_perspective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debate.vivaadperspective')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='debate.vivaadscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vivaad_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VivaadEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('criteria_scores', models.JSONField(default=dict, help_text='Scores across 6 dimensions: evidence_use, policy_reasoning, risk_awareness, people_impact, practicality, ethical_consideration')),
                ('what_you_did_well', models.JSONField(default=list)),
                ('try_next_time', models.JSONField(default=list)),
                ('tradeoffs_analysis', models.TextField(blank=True, default='')),
                ('source_backed_notes', models.JSONField(default=list, help_text='Notes with exact page references where applicable')),
                ('competency_deltas', models.JSONField(default=dict, help_text='Map of subskill_code to score change')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_record', to='debate.vivaadsession')),
            ],
        ),
        migrations.CreateModel(
            name='VivaadDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_id', models.CharField(max_length=100)),
                ('selected_option_label', models.CharField(max_length=255)),
                ('reasoning', models.TextField(help_text="Learner's justification explaining trade-offs and mitigation")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_record', to='debate.vivaadsession')),
            ],
        ),
        migrations.CreateModel(
            name='VivaadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='vivaad_docs/')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(default='PDF', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('page_count', models.IntegerField(default=1)),
                ('extracted_text', models.TextField()),
                ('chunks', models.JSONField(default=list, help_text='List of structured chunks: [{chunk_id, page_number, section_title, text}]')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vivaad_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vivaadscenario',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='debate.vivaadsource'),
        ),
        migrations.CreateModel(
            name='VivaadTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(default=1)),
                ('speaker_type', models.CharField(choices=[('LEARNER', 'Learner'), ('PERSPECTIVE', 'Perspective')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('perspective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debate.vivaadperspective')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='debate.vivaadsession')),
            ],
            options={
                'ordering': ['turn_number', 'timestamp'],
            },
        ),
    ]
