# Generated by Django 6.1 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialprofile',
            name='career_goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='confirmed_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='current_role',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='extracted_resume_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='raw_resume_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='officialprofile',
            name='target_role',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
