# Generated by Django 5.0.14 on 2026-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_officialprofile_career_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Official email address (unique identifier)', max_length=254, unique=True),
        ),
    ]
