# Generated by Django 6.1 on 2026-09-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buddy_language',
            field=models.CharField(default='en', help_text='Language preference for Neeti Saarthi Buddy', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='buddy_voice_enabled',
            field=models.BooleanField(default=True, help_text='Whether voice output is enabled for Neeti Saarthi Buddy'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_tour_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed or dismissed the Neeti Saarthi Buddy tour'),
        ),
    ]
